### ISSUE TITLE
File present on create but not edit

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/file-field_type#1]
Create I can see the header Image

![screen shot 2015-07-02 at 5 31 40 pm](https://cloud.githubusercontent.com/assets/535135/8490061/579c8562-20e0-11e5-9089-c302b95ca2dd.png)

Edit the header image is gone

![screen shot 2015-07-02 at 5 31 52 pm](https://cloud.githubusercontent.com/assets/535135/8490066/62e16b7c-20e0-11e5-8b48-06124d33a0d8.png)

**Comment by RyanThompson** [comment]
Can you show me some code?

What is the dump of the $builder->getFields() just before the factory loop - in FieldBuilder (Form namespace).

**Comment by bloveless** [comment]
https://github.com/bloveless/stashes-module

**Comment by bloveless** [comment]
I'll send the dumps in a second here.

**Comment by bloveless** [comment]
https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Ui/Form/Component/Field/FieldBuilder.php#L70

<img width="339" alt="screen shot 2015-07-05 at 9 41 03 pm" src="https://cloud.githubusercontent.com/assets/535135/8515379/a51cd8f2-235e-11e5-8886-780be2c33378.png">

**Comment by bloveless** [comment]
It doesn't seem to have the file in the field list.

**Comment by bloveless** [comment]
I'm sure that this is going to be a streams issues now.

/admin/stashes/create with the dd in the same location as before 

![screen shot 2015-07-06 at 9 40 34 am](https://cloud.githubusercontent.com/assets/535135/8526295/13ff92d2-23c3-11e5-9095-8414e170be69.png)

**Comment by RyanThompson** [comment]
Hm.. In the FieldBuilder - on edit - I assume it's in the fields BEFORE the input call right?

Is it there if you dump fields from the builder here: https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Ui/Form/Component/Field/FieldBuilder.php#L68

What about AFTER the input() method

**Comment by bloveless** [comment]
Before I get just a * and after is the second array.

<img width="431" alt="screen shot 2015-07-06 at 3 08 47 pm" src="https://cloud.githubusercontent.com/assets/535135/8533231/ec9a7738-23f0-11e5-8458-1cc559835276.png">

**Comment by RyanThompson** [comment]
Ok, so here's where it's messing up: https://github.com/anomalylabs/streams-platform/blob/1.0/develop/src/Ui/Form/Component/Field/FieldFiller.php

**Comment by RyanThompson** [comment]
See what you can find - ping me if you want personaly

**Comment by RyanThompson** [comment]
Pulled your module - yer high! lol

**Comment by bloveless** [comment]
I can't believe that it was because I was cross Referencing modules. Thanks for the help @RyanThompson
