### ISSUE TITLE
Current Value not set in Edit Forms

### ISSUE THREAD

**Issue by joselfonseca** [anomalylabs/file-field_type#7]
![screen shot 2015-08-24 at 4 36 00 pm](https://cloud.githubusercontent.com/assets/2046653/9453215/663ed008-4a7e-11e5-8f00-109fea5c5e9a.png)
When editing a page, post or stream that has a file field type, it does not takes the current value, i have to select the image again to be able to continue.

**Comment by RyanThompson** [comment]
Im on it!

**Comment by RyanThompson** [comment]
Fixed
