### ISSUE TITLE
Specifying mime types for file type config produces an error on save

### ISSUE THREAD

**Issue by gavinfostered** [anomalylabs/file-field_type#9]
When specifying mime types in a migration file for an addon (a block extension in my case) the user is unable to save when using an image of type .jpg but can save when the image is of type .png. 

##Replicate

Config => image => true
Config => mimes => 'jpg', 'png'

##Example

```
protected $fields = [
        'image' => [
            'type'   => 'anomaly.field_type.file',
            'config' => [
                'disk'  => 'panels',
                'image' => true,
                'mimes' => [
                    'jpg',
                    'png'
                ],
                'max'   => 10
            ]
        ]
    ];
```

##Errors

* If .jpg image is used, user will receive an error stating file type must be of type .jpg or .png
* The image will still successfully get uploaded to the specified disk
* The image id will still get entered into the db, but the entry isn't saved
* If .png image is used, user will receive no error, entry is saved as expected

**Comment by joselfonseca** [comment]
Have you try adding jpeg as well?. Had the same situation and even the image was .jpg but the mime was jpeg.

**Comment by gavinfostered** [comment]
Brilliant point! Going to try now.

**Comment by RyanThompson** [comment]
This should look / detect / ensure both!

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/file-field_type/commit/028a019d64da7e297193bc1f2195f496f6c30fd1
